# Generated by Django 4.0.5 on 2023-02-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_service_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
