# Generated by Django 4.0.5 on 2023-02-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
