# Generated by Django 4.0.5 on 2023-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_service_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_duration',
            field=models.IntegerField(blank=True),
        ),
    ]
