# Generated by Django 4.0.5 on 2023-02-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_service_image_servicecategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
