# Generated by Django 4.0.5 on 2023-02-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_service_image_alter_servicecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
