# Generated by Django 4.0.5 on 2023-02-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_employeeservice_delete_employee_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_description',
        ),
    ]
