# Generated by Django 4.0.5 on 2023-02-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_servicecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='category',
            field=models.ManyToManyField(to='app1.servicecategory'),
        ),
    ]
