# Generated by Django 4.0.5 on 2023-02-25 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_users_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
