# Generated by Django 4.0.5 on 2023-02-25 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_delete_employeeservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='employee',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
