# Generated by Django 4.0.5 on 2023-02-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_servicecategory_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='employee',
        ),
        migrations.AddField(
            model_name='users',
            name='category',
            field=models.ManyToManyField(to='app1.servicecategory'),
        ),
    ]
