# Generated by Django 4.0.5 on 2023-02-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_userscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersCategory',
        ),
    ]
