# Generated by Django 4.0.5 on 2023-02-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_employeeservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeservice',
            name='employee',
        ),
    ]
