# Generated by Django 4.0.5 on 2023-02-25 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_remove_employeeservice_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservice',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
