# Generated by Django 4.0.5 on 2023-02-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_employeeservice_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='category',
            field=models.ManyToManyField(related_name='users', to='app1.servicecategory'),
        ),
        migrations.DeleteModel(
            name='EmployeeService',
        ),
    ]
