# Generated by Django 4.0.5 on 2023-05-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_reservationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationDate',
        ),
    ]
