# Generated by Django 4.0.5 on 2023-05-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_appointment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment2',
        ),
    ]
