# Generated by Django 4.0.5 on 2023-05-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_date_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
