# Generated by Django 4.0.5 on 2023-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Washing and hairstyle', 'Washing and hairstyle'), ('Hair coloring', 'Hair coloring'), ("Classic women's hairstyle", "Classic women's hairstyle"), ('Only washing', 'Only washing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('08 AM', '08 AM'), ('09 AM', '09 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 AM', '12 AM'), ('1 PM', '1 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM')], default='8 AM', max_length=10),
        ),
    ]
