# Generated by Django 4.0.5 on 2023-05-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_alter_appointment_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
    ]
