# Generated by Django 4.0.5 on 2023-05-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_rename_date_appointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Washing and hairstyle', 'Washing and hairstyle'), ('Hair coloring', 'Hair coloring'), ("Classic women's hairstyle", "Classic women's hairstyle"), ('Only washing', 'Only washing')], max_length=255),
        ),
    ]
