# Generated by Django 4.0.5 on 2023-05-17 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_appointment_employee_alter_appointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service2', models.CharField(choices=[('Washing and hairstyle', 'Washing and hairstyle'), ('Hair coloring', 'Hair coloring'), ("Classic women's hairstyle", "Classic women's hairstyle"), ('Only washing', 'Only washing')], max_length=255)),
                ('date2', models.DateField()),
                ('time2', models.CharField(choices=[('08 AM', '08 AM'), ('09 AM', '09 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 AM', '12 AM'), ('1 PM', '1 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM')], default='8 AM', max_length=10)),
                ('time_ordered2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_reservation', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
