# Generated by Django 4.0.5 on 2023-05-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_appointment2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment2',
            old_name='date2',
            new_name='date',
        ),
    ]
