# Generated by Django 4.0.5 on 2023-05-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_rename_date2_appointment2_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment2',
            name='time_ordered2',
        ),
    ]
