# Generated by Django 4.0.5 on 2023-06-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_remove_appointment2_time_ordered2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_duration',
            field=models.TimeField(),
        ),
    ]
