# Generated by Django 4.0.5 on 2023-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_service_service_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Appointment2',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
    ]
