# Generated by Django 4.0.5 on 2023-06-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_remove_hours_date_rename_day_appointment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
