# Generated by Django 4.0.5 on 2023-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='testDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateField()),
            ],
        ),
    ]
