# Generated by Django 4.0.5 on 2023-06-15 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_testdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdate',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
