# Generated by Django 4.0.5 on 2023-06-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_duration',
            field=models.DurationField(),
        ),
    ]
