# Generated by Django 4.0.5 on 2023-08-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_alter_appointment_employee_alter_appointment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
