# Generated by Django 4.0.5 on 2023-08-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_alter_appointment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
