# Generated by Django 4.0.5 on 2023-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_alter_appointment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True),
        ),
    ]
